### your site title here

title: The Libertine Society
url: "https://thelibertinesociety.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: # the subpath of your site, e.g. "/blog"
repository: "thelibertinesociety/thelibertinesociety.github.io"
email: libertinesocietypdx@gmail.com




highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
# analytics:

# Comments
disqus_shortname: thelibertinesociety


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


# `collections` are sort of like little subsections of the site.
# they can be listed like this...
#   {% for x in site.cupcakes %}
#     - <a href="{{x.url | prepend: site.baseurl}}">{{x.title}}</a>
#   {% endfor %}
collections:
  cupcakes:
    output: true
  cookies:
    output: true
  documents:
    output: true

sass:
 style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]
